select *,
SUM(salary) over (order by EmpID
				rows between 2 preceding and 2 following) as Running_total
from Employees

-- moving avg
select *,
AVG(salary) over (order by EmpID rows between 2 preceding and current row) as MA
from Employees


--1 Assign a row number to each order within each region sorted by descending orderselect [Order ID], Region, Sales,ROW_NUMBER () OVER (partition by region order by sales desc)from Orders--2 Rank customers within each region by total salesselect [Customer ID],[Customer Name], Region, SUM(Sales) AS TS,rank () over (PARTITION BY REGION order by SUM(sales) desc) Rankfrom Ordersgroup by Region,[Customer ID],[Customer Name]--3 Find the dense rank of each product by profit in each categoryselect [Product ID], category, sum(profit),DENSE_RANK () over (partition by category order by sum(profit) desc) Rankfrom Ordersgroup by [Product ID], category--4 for each order, find the next order date by same customerselect [Customer id],  [Order ID], [Order Date],lead ([Order Date]) over (partition by [Customer id] order by [order date]) Next_order_datefrom Orders--5 for each order, find the previous order's profit by the same customerselect [Order ID], [Customer id], sum(Profit),[Order Date],lag (sum(profit)) over (partition by [Customer id] order by [order date]) previous_Profitfrom Ordersgroup by [Order ID], [Order Date],  [Customer id]--6 calculate the running total of sales for each region by order dateselect region, [Order Date],Sales,sum(sales) over (partition by region order by [order date]	rows between unbounded preceding and current row) as RTfrom Orders--7 compute the cumulative average profit for each sub-category based on order dateselect [Sub-Category], [Order Date], sum(Profit),avg(sum(profit)) over (partition by [sub-category] order by [order date]	rows between unbounded preceding and current row) as MAfrom Ordersgroup by [Sub-Category], [Order Date]--8 find the difference in sales between each order and the previous order for each customer select [Customer ID], [Order Date] , sum(sales) as TSlag(sum(sales)) over (partition by [customer id] order by [order date]) as previous,sum(sales) - lag(sum(sales), 1, 0) over (partition by from Ordersselect *,first_value(empname) over (order by empid) as first_empfrom Employees-- find the employee who the join first in the deptselect *,first_value(emp_name) over (partition by dept_name order by emp_id) as first_empfrom Employees2-- find the last emp to join the deptselect *,last_value(emp_name) over (partition by dept_name order by emp_id							rows between unbounded preceding and unbounded following) as last_empfrom Employees2